# Generated by Django 5.2.8 on 2025-12-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('vendas', '0002_remove_itemvenda_subtotal_remove_venda_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.cliente'),
        ),
    ]
